version: '2'
services:
  db:
    image: postgres:latest 
    restart: always
    environment:
      POSTGRES_DB: storybook_development
      POSTGRES_PASSWORD: root
    container_name: postgre 
  rails:
    tty: true
    stdin_open: true
    command: sh -c "rm -r tmp; bundle install; bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    image: storybook_backend 
    depends_on:
      - db 
    ports:
      - 0.0.0.0:3000:3000
    environment:
      DB_HOST: postgree 
    container_name: storybook_backend
