default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: root
  pool: 5

development:
  <<: *default
  database: storybook_development


test:
  <<: *default
  database: storybook_test
